"""BepInEx 5 -- the v1 adapter, covering Mono Unity games.

Deploy shape: a single plugin DLL copied into `BepInEx/plugins`. Log: the
single fixed `BepInEx/LogOutput.log`. This is the simplest shape on the
roadmap, which is why it goes first: MelonLoader, Hollow Knight's Modding API
and Beat Saber's BSIPA all reuse it, differing only in where they look.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import replace
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

from modwright.errors import (
    ArtifactLockedError,
    BuildFailedError,
    Il2CppUnsupportedError,
    InvalidDeployRootError,
    InvalidModNameError,
    ModReferenceNotFoundError,
    ProjectExistsError,
)
from modwright.models import (
    BuildOutcome,
    DeployOutcome,
    GameContext,
    LoaderInfo,
    LoggingStatus,
    PatchTarget,
)
from modwright.mods import find_installed_mod
from modwright.patches import extract_harmony_targets

#: Mod names become both an assembly name and a C# namespace, so they are held
#: to C# identifier rules rather than silently mangled into something that
#: compiles to a different name than the user asked for.
_VALID_MOD_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

#: The split between this file and the .csproj is what is true of THIS
#: MACHINE versus what is true of the project. The .csproj holds what the mod
#: *is* -- target framework, assembly name, version -- which is true anywhere
#: and is the user's to hand-edit, so it is written once at scaffold time and
#: never rewritten. Absolute paths and the location of installed dependencies
#: are true only here, so they live in this file, which ModWright owns.
#:
#: It is regenerated wholesale rather than patched. That needs no XML parsing,
#: so it cannot corrupt a file somebody reformatted, and it makes the contents
#: a pure function of the project config -- there is no half-updated state to
#: land in, where a switched loader sits beside a reference that was left
#: behind.
#:
#: Note the loader path is NOT derived from the game path. A mod manager keeps
#: its loader in a profile far outside the install, and deriving one from the
#: other is what silently compiled mods against a different BepInEx from the
#: one they ran under.
PROPS_FILENAME = "Modwright.props"

_PROPS_IMPORT = (
    f'  <Import Project="{PROPS_FILENAME}" '
    f"Condition=\"Exists('{PROPS_FILENAME}')\" />"
)

_PROPS_TEMPLATE = r"""<Project>

  <!--
    GENERATED BY MODWRIGHT. Edits here are overwritten.

    Paths this machine builds against, and the other mods this project
    compiles against. LoaderDir is where BepInEx itself lives, which is NOT
    always inside the game: a mod manager keeps each profile as its own
    loader tree, and the mod must compile against the BepInEx it will
    actually run under. Every path is overridable, so this project still
    builds on another machine:

        dotnet build -c Release -p:GameDir="D:\Games\__GAME_FOLDER__"
  -->
  <PropertyGroup>
    <GameDir Condition="'$(GameDir)' == ''">__GAME_DIR__</GameDir>
    <LoaderDir Condition="'$(LoaderDir)' == ''">__LOADER_DIR__</LoaderDir>
    <ModsDir Condition="'$(ModsDir)' == ''">__MODS_DIR__</ModsDir>
    <GameManagedDir>$(GameDir)\__DATA_FOLDER__\Managed</GameManagedDir>
    <BepInExCoreDir>$(LoaderDir)\BepInEx\core</BepInExCoreDir>
  </PropertyGroup>

  <ItemGroup>
__REFERENCES__
  </ItemGroup>

</Project>
"""

_CSPROJ_TEMPLATE = """<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>__TFM__</TargetFramework>
    <AssemblyName>__MOD_NAME__</AssemblyName>
    <RootNamespace>__MOD_NAME__</RootNamespace>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!--
    Where the game and the loader actually live is machine-specific, and it
    changes: switching to another mod-manager profile moves the loader. So
    those paths are NOT here. This file is written once and is yours to edit,
    which means a path baked into it would quietly go stale. They live in
    __PROPS_FILE__ instead, which ModWright regenerates.
    (MSBuild rejects a double hyphen inside an XML comment, so this text
    avoids one.)
  -->
  <Import Project="__PROPS_FILE__" Condition="Exists('__PROPS_FILE__')" />

  <!-- Without that file every path below resolves to nothing, and the build
       fails with a pile of "type or namespace not found" errors that say
       nothing about the real cause. Say the real cause instead. -->
  <Target Name="ModwrightRequireProps" BeforeTargets="PrepareForBuild">
    <Error Condition="!Exists('$(MSBuildThisFileDirectory)__PROPS_FILE__')"
           Text="__PROPS_FILE__ is missing, so this project does not know where the game or the mod loader are on this machine. It is generated, and deliberately not committed, because it contains absolute paths. Regenerate it with ModWright: set_game_install (and set_deploy_target if mods run through a manager)." />
  </Target>

  <!-- Assemblies are referenced straight out of the install, so the mod
       compiles against exactly the versions it will run against, with no
       NuGet feed required. Private="false" keeps game and loader assemblies
       out of the build output; only the mod's own DLL should be deployed. -->
  <ItemGroup>
    <Reference Include="$(BepInExCoreDir)\\BepInEx.dll" Private="false" />
    <Reference Include="$(BepInExCoreDir)\\0Harmony.dll" Private="false" />
    <Reference Include="$(GameManagedDir)\\Assembly-CSharp*.dll" Private="false" />
    <Reference Include="$(GameManagedDir)\\UnityEngine*.dll" Private="false" />
    <Reference Include="$(GameManagedDir)\\Unity.*.dll" Private="false" />
  </ItemGroup>

</Project>
"""

_PLUGIN_TEMPLATE = """using BepInEx;
using BepInEx.Logging;
using HarmonyLib;

namespace __MOD_NAME__;

[BepInPlugin(PluginGuid, PluginName, PluginVersion)]
public class Plugin : BaseUnityPlugin
{
    // Must be unique across every mod the user has installed. Change the
    // "com.example" part to something you own.
    public const string PluginGuid = "__PLUGIN_GUID__";
    public const string PluginName = "__MOD_NAME__";
    public const string PluginVersion = "1.0.0";

    internal static new ManualLogSource Logger;

    private readonly Harmony _harmony = new Harmony(PluginGuid);

    private void Awake()
    {
        Logger = base.Logger;

        // Applies every [HarmonyPatch]-annotated class in this assembly.
        _harmony.PatchAll();

        Logger.LogInfo($"{PluginName} {PluginVersion} loaded.");
    }
}
"""

#: The two generated files are excluded because they hold absolute paths on
#: one person's machine. A mod repo pushed anywhere public must not publish
#: where its author keeps their games -- the deploy path alone gives away the
#: username, the mod manager, and the profile name. Both are rebuilt from the
#: committed config plus one answer about where things live here.
_MOD_GITIGNORE = f"""bin/
obj/

# Local to this machine: absolute paths to the game and mod loader.
{PROPS_FILENAME}
.modwright.local.json
"""

#: Compiler diagnostics look like `Plugin.cs(12,9): error CS0103: ...`.
_COMPILER_ERROR = re.compile(r"^.*?: (?:error|warning) [A-Z]+\d+: .*$", re.MULTILINE)


def _compiler_errors(build_output: str, limit: int = 15) -> list[str]:
    """Pull the actual diagnostics out of MSBuild's verbose output.

    A failed build otherwise returns hundreds of lines of restore chatter, and
    the two lines that say what is wrong get lost in it.
    """
    seen: list[str] = []
    for match in _COMPILER_ERROR.findall(build_output):
        line = match.strip()
        if "error" in line and line not in seen:
            seen.append(line)
    return seen[:limit]


def _read_ini_flag(path: Path, section: str, key: str) -> bool | None:
    """Read one boolean out of an ini-shaped config file.

    Returns None -- never a guess -- when the file, section, key, or value
    cannot be read, so a caller can tell "positively off" from "no idea".

    Hand-rolled rather than `configparser` because this runs inside a failure
    diagnosis, where anything that raises replaces a confusing answer with no
    answer at all. BepInEx.cfg is ini-*ish*, not ini, and configparser's
    defaults are hostile to it: a `%` anywhere in a value trips string
    interpolation, and a repeated key trips strict mode. Using it safely would
    mean disabling both and still wrapping the call in a blanket `except` --
    more machinery than reading the single key we actually want, and a bare
    except would swallow real bugs along with the malformed configs.
    """
    try:
        # utf-8-sig so a byte-order mark cannot glue itself to the first
        # section header and make it never match.
        text = path.read_text(encoding="utf-8-sig", errors="replace")
    except OSError:
        return None

    wanted = f"[{section}]"
    in_section = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("["):
            in_section = line == wanted
        elif in_section and "=" in line and not line.startswith("#"):
            name, _, value = line.partition("=")
            if name.strip() != key:
                continue
            match value.strip().lower():
                case "true":
                    return True
                case "false":
                    return False
                case _:
                    return None  # Present but unreadable: claim nothing.
    return None


class BepInEx5Adapter:
    framework_id = "bepinex5"
    display_name = "BepInEx 5"
    # BepInEx mods are a loose DLL copied into a loader tree, and that tree
    # can live anywhere -- the game folder or any mod-manager profile.
    supports_deploy_target = True

    def inspect_game(self, install_root: Path) -> GameContext | None:
        """Whether this is a game this framework could mod, loader aside.

        Deliberately says nothing about where mods go: the loader may not be
        in the game folder at all. `mods_dir` is therefore None here, and is
        filled in by whoever establishes which loader tree is in use.
        """
        data_dirs = sorted(install_root.glob("*_Data"))
        if not data_dirs:
            return None  # Not a Unity install; some other adapter may claim it.

        # IL2CPP compiles game logic to native code, leaving Assembly-CSharp.dll
        # as a metadata-only stub. No IL decompiler can read it, so refuse
        # loudly instead of scaffolding a mod against a shell.
        if (install_root / "GameAssembly.dll").exists():
            raise Il2CppUnsupportedError(
                f"{install_root.name} is an IL2CPP game, which ModWright cannot "
                "inspect: its real logic is compiled to native code, not IL.",
                hints=[
                    "IL2CPP support needs a separate toolchain (Cpp2IL / "
                    "Il2CppInterop) and is out of scope.",
                ],
            )

        managed_dir = data_dirs[0] / "Managed"
        if not (managed_dir / "Assembly-CSharp.dll").exists():
            return None

        return GameContext(
            install_root=install_root,
            game_name=install_root.name,
            framework_id=self.framework_id,
            managed_dir=managed_dir,
        )

    def detect(self, install_root: Path) -> GameContext | None:
        """Structural sniff of a Unity install root.

        Returns None (rather than raising) whenever the install simply isn't
        ours, so the registry can keep trying. The one exception is IL2CPP: the
        user pointed at a real Unity game we positively cannot support, and
        saying so beats silently falling through to "unsupported game".

        Being a Mono Unity game is NOT on its own enough to claim: RimWorld and
        Cities: Skylines are both Unity+Mono and load mods natively, with no
        BepInEx anywhere. So some evidence of this loader is still required --
        it just no longer has to be inside the game folder.
        """
        context = self.inspect_game(install_root)
        if context is None:
            return None

        info = self.inspect_loader_root(install_root)
        if info is not None:
            return replace(context, mods_dir=info.mods_dir)

        if self._launched_through_doorstop(install_root):
            # The loader is installed somewhere else and the game is started
            # pointed at it -- which is what a mod manager does, and what it
            # leaves behind in the game folder. Enough to know the framework;
            # not enough to know WHICH tree, so mods_dir stays unset until the
            # user says. Choosing one for them is what silently deployed into
            # a dead folder before.
            return context

        return None

    @staticmethod
    def _launched_through_doorstop(install_root: Path) -> bool:
        """Whether this game is started through an external BepInEx loader.

        BepInEx injects via Doorstop, which needs its proxy DLL and config
        beside the executable even when everything else lives in a profile.
        Both are required: `winhttp.dll` alone is a common enough filename to
        mean nothing on its own.
        """
        return (install_root / "winhttp.dll").is_file() and (
            install_root / "doorstop_config.ini"
        ).is_file()

    def inspect_loader_root(self, loader_root: Path) -> LoaderInfo | None:
        loader_dir = loader_root / "BepInEx"
        if not (loader_dir / "core").is_dir():
            # Either not a BepInEx tree at all, or one with no loader in it.
            # Both are unusable, and discovery should offer neither.
            return None
        log_path = loader_dir / "LogOutput.log"
        return LoaderInfo(
            mods_dir=loader_dir / "plugins",
            log_path=log_path if log_path.exists() else None,
        )

    #: What to install in a mod manager to get BepInEx and nothing else.
    #: Installing a gameplay mod also pulls it in, as a dependency, but drags
    #: that mod and its own dependencies along with it -- which is how a
    #: profile meant for testing one mod ends up with six.
    _LOADER_PACKAGE = "BepInExPack"

    def explain_unusable_loader_root(self, loader_root: Path) -> str | None:
        loader_dir = loader_root / "BepInEx"
        if not loader_dir.is_dir():
            return (
                "No BepInEx here yet, which is the normal state of a profile "
                f"nothing has been installed into. Install {self._LOADER_PACKAGE} "
                "into it through the mod manager: that is the loader on its "
                "own, so the profile stays empty apart from the mod being "
                "developed and its log stays readable."
            )
        if not (loader_dir / "core").is_dir():
            return (
                "BepInEx is here but BepInEx/core is missing, so the loader "
                "itself is absent -- this tree would accept a deployed file "
                f"and load nothing. Reinstall {self._LOADER_PACKAGE} into it."
            )
        return None

    def adopt_loader_root(
        self, game_context: GameContext, loader_root: Path
    ) -> GameContext:
        """Redirect deploy and logs at a mod-manager profile.

        A profile is recognised the same way an install is -- by containing a
        BepInEx tree -- rather than by living under a path we recognise, so
        this works for managers ModWright has never heard of and for a loader
        tree assembled by hand.
        """
        if not loader_root.exists():
            # Distinct from a wrong path: this is usually a target that was
            # valid when it was chosen and has since been deleted or renamed.
            raise InvalidDeployRootError(
                f"{loader_root} no longer exists.",
                hints=[
                    "If this was a mod-manager profile, it may have been "
                    "deleted or renamed. Pick another with list_mod_profiles, "
                    "or recreate it in the mod manager.",
                ],
            )

        loader_dir = loader_root / "BepInEx"
        if not loader_dir.is_dir():
            # A profile with no BepInEx is the normal state of a NEW profile:
            # managers do not install the loader until the first mod is added.
            raise InvalidDeployRootError(
                f"{loader_root} has no BepInEx installed.",
                hints=[
                    # Leads with the loader-only package deliberately. The
                    # "install any mod" version of this hint is what put a
                    # debug menu into a test profile, where it fought the mod
                    # under development for the same field.
                    f"If this is a new profile, install {self._LOADER_PACKAGE} "
                    "into it through the mod manager -- that is BepInEx on its "
                    "own, and leaves the profile clean for testing.",
                    "If this was meant to be a game install, check the path.",
                ],
            )
        # `core` holds the loader itself. Without it the tree is a shell --
        # exactly the state that accepted a deployed DLL and loaded nothing.
        if not (loader_dir / "core").is_dir():
            raise InvalidDeployRootError(
                f"{loader_root} has a BepInEx folder but no BepInEx/core, so "
                "the loader itself is missing.",
                hints=[
                    "Nothing deployed here would load. Reinstall BepInEx into "
                    "this profile, or pick another with list_mod_profiles.",
                ],
            )

        return replace(
            game_context,
            loader_root=loader_root,
            mods_dir=loader_dir / "plugins",
        )

    def scaffold(
        self, project_path: Path, game_context: GameContext, mod_name: str
    ) -> list[Path]:
        """Write a mod project wired to this specific game install.

        The .csproj is generated rather than produced by `dotnet new
        bepinex5plugin`: BepInEx's template needs a custom NuGet feed installed
        first, pins its own dependency versions rather than the ones this game
        actually ships, and deliberately leaves game references for the
        developer to add -- so it would need post-processing anyway.
        """
        if not _VALID_MOD_NAME.match(mod_name):
            raise InvalidModNameError(
                f"{mod_name!r} is not usable as an assembly name and namespace.",
                hints=[
                    "Use letters, digits and underscores, starting with a "
                    "letter or underscore. Example: MyFirstMod",
                ],
            )

        assert game_context.managed_dir is not None  # guaranteed by detect()
        project_path.mkdir(parents=True, exist_ok=True)

        existing = list(project_path.glob("*.csproj"))
        if existing:
            raise ProjectExistsError(
                f"{project_path} already contains {existing[0].name}.",
                hints=["Choose an empty directory, or delete the existing project."],
            )

        csproj_text = (
            _CSPROJ_TEMPLATE.replace("__TFM__", self._target_framework(game_context))
            .replace("__MOD_NAME__", mod_name)
            .replace("__PROPS_FILE__", PROPS_FILENAME)
        )
        plugin_text = _PLUGIN_TEMPLATE.replace("__MOD_NAME__", mod_name).replace(
            "__PLUGIN_GUID__", f"com.example.{mod_name.lower()}"
        )

        written: list[Path] = []
        for relative, content in (
            (f"{mod_name}.csproj", csproj_text),
            ("Plugin.cs", plugin_text),
            (".gitignore", _MOD_GITIGNORE),
        ):
            path = project_path / relative
            path.write_text(content, encoding="utf-8")
            written.append(path)

        # The build paths live here, not in the .csproj, so this is not
        # optional -- without it the project has no idea where the game or the
        # loader are.
        written.append(self.write_project_props(project_path, game_context, []))
        return written

    @staticmethod
    def _target_framework(game_context: GameContext) -> str:
        """Match the target to the BCL the game actually ships.

        This is about which reference assemblies exist, not about what Mono can
        load: Unity ships a netstandard 2.1 facade under either Api
        Compatibility Level, so `netstandard.dll` alone does not discriminate
        and a netstandard2.1 plugin will generally load either way.

        What differs is the BCL. Under the .NET Framework profile the game
        ships the full set (System.Data, System.Xml.Linq, System.Net.Http);
        targeting net472 makes those available to the mod, and matches what
        BepInEx 5 and the overwhelming majority of Mono-Unity mods target.
        Under the .NET Standard profile those assemblies are absent, so net472
        would promise a BCL that is not there and netstandard2.1 is correct.
        """
        assert game_context.managed_dir is not None
        framework_markers = ("System.Data.dll", "System.Xml.Linq.dll")
        if all((game_context.managed_dir / m).exists() for m in framework_markers):
            return "net472"
        if (game_context.managed_dir / "netstandard.dll").exists():
            return "netstandard2.1"
        # Neither profile is recognisable; net472 is the safer guess, since
        # BepInEx 5 itself targets .NET Framework.
        return "net472"

    def build(self, project_path: Path) -> BuildOutcome:
        """Compile the mod with `dotnet build`.

        The produced assembly is located by asking MSBuild for `TargetPath`
        rather than guessing `bin/Release/<tfm>/<name>.dll` -- mod projects
        target unusual frameworks and the folder name varies with them.
        """
        project_file = self._project_file(project_path)

        result = self._run_dotnet(["build", str(project_file), "-c", "Release"])
        if result.returncode != 0:
            raise BuildFailedError(
                "dotnet build failed.",
                hints=_compiler_errors(result.stdout) or [result.stdout[-1500:]],
            )

        # Evaluated, not rebuilt: this reads the property off the project that
        # was just built.
        query = self._run_dotnet(
            ["msbuild", str(project_file), "-getProperty:TargetPath", "-p:Configuration=Release"]
        )
        target_path = query.stdout.strip()
        if query.returncode != 0 or not target_path:
            raise BuildFailedError(
                "Build succeeded but the output assembly could not be located.",
                hints=[query.stdout[-1000:] or query.stderr[-1000:]],
            )

        artifact = Path(target_path)
        if not artifact.exists():
            raise BuildFailedError(
                f"MSBuild reported an output at {artifact}, but it does not exist."
            )

        return BuildOutcome(artifact=artifact, log=result.stdout[-2000:])

    @staticmethod
    def _project_file(project_path: Path) -> Path:
        projects = sorted(project_path.glob("*.csproj"))
        if not projects:
            raise BuildFailedError(
                f"No .csproj found in {project_path}.",
                hints=["Run scaffold_mod_project first."],
            )
        if len(projects) > 1:
            raise BuildFailedError(
                f"{project_path} contains {len(projects)} .csproj files.",
                hints=["ModWright expects one project per mod directory."],
            )
        return projects[0]

    @staticmethod
    def _run_dotnet(args: list[str]) -> subprocess.CompletedProcess[str]:
        try:
            return subprocess.run(
                ["dotnet", *args],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except FileNotFoundError as exc:
            raise BuildFailedError(
                "The `dotnet` command was not found.",
                hints=["Install the .NET SDK and ensure `dotnet` is on PATH."],
            ) from exc

    def deploy(
        self, outcome: BuildOutcome, game_context: GameContext
    ) -> DeployOutcome:
        """Copy the plugin DLL into `BepInEx/plugins`."""
        if outcome.deployed_by_build or outcome.artifact is None:
            raise ValueError(
                "BepInEx 5 builds always produce a separate artifact to deploy."
            )

        plugins_dir = game_context.mods_dir
        assert plugins_dir is not None  # guaranteed by detect()
        # Create `plugins` if BepInEx is there but has never been populated;
        # never conjure the whole tree. `parents=True` on a mistyped root
        # would build a directory nothing ever loads from and report success.
        if not plugins_dir.is_dir():
            if not plugins_dir.parent.is_dir():
                raise InvalidDeployRootError(
                    f"{plugins_dir.parent} does not exist, so {plugins_dir} "
                    "is not a place this game loads mods from.",
                    hints=["Check the deploy target with list_mod_profiles."],
                )
            plugins_dir.mkdir()
        destination = plugins_dir / outcome.artifact.name

        try:
            shutil.copy2(outcome.artifact, destination)
        except (PermissionError, OSError) as exc:
            # Windows raises a sharing violation (WinError 32) when the game
            # holds the DLL open. That is the overwhelmingly common cause, and
            # a plain stack trace hides it.
            raise ArtifactLockedError(
                f"Could not write {destination.name}: the file is locked.",
                hints=[
                    f"{game_context.game_name} is probably running -- close it "
                    "and deploy again.",
                    f"Underlying error: {exc}",
                ],
            ) from exc

        return DeployOutcome(destination=destination, copied=True)

    def write_project_props(
        self,
        project_path: Path,
        game_context: GameContext,
        packages: list[str],
    ) -> Path:
        """Regenerate the file holding every path and reference ModWright owns.

        Rewritten wholesale from the current context rather than patched, so
        the paths in it cannot drift from the target the project is actually
        set to. This is why they are not in the .csproj: that is written once
        and never touched again, which is right for a template the agent works
        on, and wrong for a fact that changes when the deploy target does.

        Assemblies are listed individually rather than globbed. A glob would
        survive a dependency reorganising its folder, but it cannot express
        the exclusions that matter: mods ship native libraries and framework
        assemblies next to their own code, and referencing either breaks the
        build. Explicit paths also fail loudly if a dependency is uninstalled,
        where a glob would quietly match nothing and produce a confusing
        error about missing types instead.
        """
        mods_dir = game_context.mods_dir
        assert mods_dir is not None  # caller resolves the target first
        assert game_context.managed_dir is not None
        entries: list[str] = []

        for package in packages:
            mod = find_installed_mod(mods_dir, package)
            if mod is None:
                raise ModReferenceNotFoundError(
                    f"{package} is not installed in {mods_dir}.",
                    hints=[
                        "Install it through the mod manager for this profile, "
                        "then add the reference again.",
                        "list_available_mods shows what is installed.",
                    ],
                )
            for assembly in mod.assemblies:
                relative = assembly.relative_to(mods_dir)
                entries.append(
                    f'    <Reference Include="$(ModsDir)\\{xml_escape(str(relative))}" '
                    'Private="false" />'
                )

        # Always written, even with no references at all: this file carries
        # the build paths too, so deleting it would break the build rather
        # than merely drop a dependency.
        assert game_context.managed_dir is not None
        target = project_path / PROPS_FILENAME
        target.write_text(
            _PROPS_TEMPLATE.replace(
                "__GAME_DIR__", xml_escape(str(game_context.install_root))
            )
            .replace(
                "__LOADER_DIR__", xml_escape(str(game_context.effective_loader_root))
            )
            .replace("__MODS_DIR__", xml_escape(str(mods_dir)))
            .replace(
                "__DATA_FOLDER__", xml_escape(game_context.managed_dir.parent.name)
            )
            .replace("__GAME_FOLDER__", xml_escape(game_context.install_root.name))
            .replace("__REFERENCES__", "\n".join(entries)),
            encoding="utf-8",
        )
        self._ensure_props_import(project_path)
        return target

    def _ensure_props_import(self, project_path: Path) -> None:
        """Add the import to a .csproj scaffolded before references existed."""
        project_file = self._project_file(project_path)
        text = project_file.read_text(encoding="utf-8")
        if PROPS_FILENAME in text:
            return
        project_file.write_text(
            text.replace("</Project>", f"{_PROPS_IMPORT}\n\n</Project>", 1),
            encoding="utf-8",
        )

    def extract_patch_targets(self, mod_source_dir: Path) -> list[PatchTarget]:
        """BepInEx mods patch via Harmony, so the shared extractor applies."""
        return extract_harmony_targets(mod_source_dir)

    def resolve_log(self, game_context: GameContext) -> Path | None:
        """The log belongs to whichever loader tree actually runs.

        With a mod-manager profile that is the profile's own LogOutput.log,
        not the game folder's -- which may be stale or never written at all.
        """
        root = game_context.effective_loader_root
        log_path = root / "BepInEx" / "LogOutput.log"
        return log_path if log_path.exists() else None

    #: Printed once per process, immediately before BepInEx loads plugins.
    #: Chosen over the version banner on the first line because that banner
    #: carries the GAME EXECUTABLE's date, not the launch time -- it reads
    #: identically in every profile on a machine, months apart, and is
    #: therefore worthless as a "did it start again" signal despite looking
    #: exactly like a timestamp.
    _CHAINLOADER_BANNER = "Chainloader started"

    def count_loader_starts(self, log_text: str) -> int:
        """How many times BepInEx began loading plugins in this text.

        Only ever meaningful over a slice read since a known cursor. BepInEx
        truncates LogOutput.log when it starts, so the whole file holds
        exactly one of these no matter how many times the game has been run.
        """
        return log_text.count(self._CHAINLOADER_BANNER)

    def inspect_logging(self, loader_root: Path) -> LoggingStatus:
        config_path = loader_root / "BepInEx" / "config" / "BepInEx.cfg"
        if not config_path.is_file():
            # BepInEx writes this file on its first run, so its absence is a
            # sign the loader has never started here. Only a sign, though:
            # an imported profile arrives with configs it never wrote.
            return LoggingStatus(disabled=False, config_path=None)

        if _read_ini_flag(config_path, "Logging.Disk", "Enabled") is False:
            return LoggingStatus(
                disabled=True,
                config_path=config_path,
                hint=(
                    f"Disk logging is turned off for this loader: "
                    f"[Logging.Disk] Enabled = false in {config_path}. "
                    "BepInEx writes no log file at all in that state, however "
                    "well the mod is running. Set it to true and relaunch."
                ),
            )
        return LoggingStatus(disabled=False, config_path=config_path)
